```{r}
library(tidyverse)
library(cluster)
library(factoextra)
library(dendextend)
```

```{r}
library(readr)
trucks <- read_csv("trucks-1.csv")
View(trucks)
```

```{r}
trucks_scaled = scale(trucks) 
summary(trucks_scaled)
```

```{r}
kmeans_recipe= recipe(~Speeding + Distance, trucks)
trucks_cleaned= bake()
```

```{r}
set.seed(64)
clusts = 
  tibble(k = 2) %>%
  mutate(
    kclust = map(k, ~kmeans(trucks_cleaned, .x)),
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment,trucks_cleaned)
  )

clusts
```

```{r}
clusters = 
  clusts %>%
  unnest(cols = c(tidied))

assignments = 
  clusts %>% 
  unnest(cols = c(augmented))

clusterings = 
  clusts %>%
  unnest(cols = c(glanced))
```

```{r}
p1 = 
  ggplot(assignments, aes(x = Distance, y = Speeding)) +
  geom_point(aes(color = .cluster), alpha = 0.8) + 
  facet_wrap(~ k)
p1
```


```{r}
set.seed(412)
clusters = kmeans(trucks_cleaned, 8)
```
```{r}
trucks = augment(clusters, trucks)
str(trucks)
```
```{r}
ggplot(trucks, aes(x=Distance,y=Speeding,color=factor(.cluster))) + geom_point() + facet_wrap(~factor(Distance))
```